version: '3.8'

services:

  # mysql
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - db:/var/lib/mysql
    
  # phpmyadmin
  phpmyadmin:
    container_name: phpadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80

  # gate
  gate:
    container_name: gate
    restart: unless-stopped
    build:
      context: ./proxy
      args:
        VELOCITY_SECRET: ${VELOCITY_SECRET}
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"

  # server-1
  server-1:
    container_name: server-1
    restart: unless-stopped
    build: ./paper
    depends_on:
      - db
    ports:
      - "25566:25565"      
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./server-1:/data

  # server-2
  server-2:
    container_name: server-2
    restart: unless-stopped
    build: ./paper
    depends_on:
      - db
    ports:
      - "25567:25565"      
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./server-2:/data

volumes:
  db: {}