version: '3.8'

services:

  # mysql
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - db:/var/lib/mysql
    
  # phpmyadmin
  phpmyadmin:
    container_name: phpadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80

  # broker
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  # gate
  gate:
    container_name: gate
    restart: unless-stopped
    build:
      context: ./proxy
      args:
        VELOCITY_SECRET: ${VELOCITY_SECRET}
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"

  # server-1
  server-1:
    container_name: server-1
    restart: unless-stopped
    build: ./paper
    depends_on:
      - db
    ports:
      - "25566:25565"      
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./server-1:/data

  # # server-2
  # server-2:
  #   container_name: server-2
  #   restart: unless-stopped
  #   build: ./paper
  #   depends_on:
  #     - db
  #   ports:
  #     - "25567:25565"      
  #   tty: true
  #   stdin_open: true
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./server-2:/data

volumes:
  db: {}