version: '3.8'

services:
  # paper
  paper:
    container_name: paper
    build: .
    ports:
      - "25600:25600"      
    tty: true
    stdin_open: true
    env_file:
      - .env
    environment:
      TYPE: PAPER
      SERVER_PORT: 25600
      VERSION: 1.21.11
      MEMORY: 8G
      EULA: true
      OVERRIDE_ICON : true
      REPLACE_ENV_VARIABLES: true
      REPLACE_ENV_VARIABLE_PREFIX: ""
      ENABLE_ROLLING_LOGS: true
      ALLOW_NETHER: false
      ANNOUNCE_PLAYER_ACHIEVEMENTS: false
      ENABLE_COMMAND_BLOCK: true
      FORCE_GAMEMODE: true
      MODE: survival
      LEVEL: lobby
      VIEW_DISTANCE: 16
      SIMULATION_DISTANCE: 16
      ONLINE_MODE: false
    volumes:
      - ./data:/data