version: '3.8'

services:

  # mysql
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - db:/var/lib/mysql
    
  # phpmyadmin
  phpmyadmin:
    container_name: phpadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80

  # paper
  paper:
    container_name: paper
    build: .
    depends_on:
      - db
    ports:
      - "25565:25565"      
    tty: true
    stdin_open: true
    env_file:
      - .env
    environment:
      TYPE: PAPER
      VERSION: 1.21.8
      MEMORY: 8G
      EULA: true
      OVERRIDE_ICON : true
      REPLACE_ENV_VARIABLES: true
      REPLACE_ENV_VARIABLE_PREFIX: ""
      ENABLE_ROLLING_LOGS: true
      ALLOW_NETHER: false
      ANNOUNCE_PLAYER_ACHIEVEMENTS: false
      ENABLE_COMMAND_BLOCK: true
      FORCE_GAMEMODE: true
      MODE: survival
      LEVEL: lobby
      VIEW_DISTANCE: 16
      SIMULATION_DISTANCE: 16
    volumes:
      - ./data:/data

volumes:
  db: {}