id: CRAZY_CRUSADER
description: Crusader with very low cooldowns
default_kit: crusader
whitelisted_kits:
- crusader
data:
  crusader:
  - SHIELD_BASH_IMPACT_ICD=0
  - SHIELD_BASH_COOLDOWN=1
  - SHIELD_BASH_MULTIPLIER=2
  - SHIELD_BASH_DAMAGE=8