id: example
description: Use the in-game "/player <playerName> data" to view data for the kit they are using
default_kit: fish
whitelisted_kits:
  - fish
blacklisted_kits:
  - brute
data:
  shared:
    - test=1.0
  default:
    - test_default=1
    - test_default_2=2
  soldier:
    - test_soldier=1
  brute:
    - test_brute=1