id: witchcraft
description: "Only potions and mages with kit data changes"
default_kit: wizard
whitelisted_kits:
- golem
- raven
- aquarius
- wizard
- snowman
- potion_master
- buff_master
- priest
- necromancer
data:
  shared:
  - MAX_MANA=200
  - currentMana=200
  golem:
  - EARTH_WALL_COST=5
  - EARTH_SHATTER_COST=25
  aquarius:
  - maxManaPots=20
  wizard:
  - CHAIN_LIGHTNING_MAX_CHAINS=6
  - LIGHTNING_STRIKE_ICD=60
  raven:
  - GUST_VECTOR_MULTIPLIER=3
  - GUST_ICD_TICKS=25
  - GUST_AOE=6
  - GUST_MANA_COST=20
  snowman:
  - SNOWBALL_MANA_COST=10
  - SNOWBALL_FROZEN_DURATION=60
  - SNOWBALL_ICD=10
  potion_master:
  - COOLDOWN=4
  buffmaster:
  - COOLDOWN=14