#!/bin/bash

# shellcheck source=start-utils
. "$(dirname "$0")/start-utils"

: "${SYNC_SKIP_NEWER_IN_DESTINATION:=${PLUGINS_SYNC_UPDATE:-true}}"
: "${REPLACE_ENV_DURING_SYNC:=true}"
: "${REPLACE_ENV_SUFFIXES:=yml,yaml,txt,cfg,conf,properties,hjson,json,tml,toml}"
: "${REPLACE_ENV_VARIABLE_PREFIX=${ENV_VARIABLE_PREFIX:=}}"
: "${REPLACE_ENV_VARIABLES_EXCLUDES:=}"
: "${REPLACE_ENV_VARIABLES_EXCLUDE_PATHS:=}"
: "${COPY_DEST:="/data"}"

set -e

if isTrue "${SYNC_SKIP_NEWER_IN_DESTINATION}"; then
  updateArg="--skip-newer-in-destination"
fi

# Log FW Start Message
log "[FW] Script Start"

# Copy Maps
: "${COPY_WORLDS_SRC:="/worlds"}"
log "[FW] Copying world files from ${COPY_WORLDS_SRC} to ${COPY_DEST}"
mc-image-helper \
  sync $updateArg \
  --replace-env-file-suffixes="${REPLACE_ENV_SUFFIXES}" \
  --replace-env-excludes="${REPLACE_ENV_VARIABLES_EXCLUDES}" \
  --replace-env-exclude-paths="${REPLACE_ENV_VARIABLES_EXCLUDE_PATHS}" \
  --replace-env-prefix="${REPLACE_ENV_VARIABLE_PREFIX}" \
  "${COPY_WORLDS_SRC}" "${COPY_DEST}"

# Copy Extras
: "${COPY_EXTRAS_SRC:="/extras"}"
log "[FW] Copying extras files from ${COPY_EXTRAS_SRC} to ${COPY_DEST}"
mc-image-helper \
  sync $updateArg \
  --replace-env-file-suffixes="${REPLACE_ENV_SUFFIXES}" \
  --replace-env-excludes="${REPLACE_ENV_VARIABLES_EXCLUDES}" \
  --replace-env-exclude-paths="${REPLACE_ENV_VARIABLES_EXCLUDE_PATHS}" \
  --replace-env-prefix="${REPLACE_ENV_VARIABLE_PREFIX}" \
  "${COPY_EXTRAS_SRC}" "${COPY_DEST}"

# Log FW Finish Message
log "[FW] Script Finish"

exec "$(dirname "$0")/start" "$@"