location: lobby:9.500:74.000:5.500
enabled: true
display-range: 48
update-range: 48
update-interval: 20
facing: 0.0
down-origin: true
pages:
- lines:
  - content: '&7- &ex2 Credits'
    height: 0.3
  - content: '&7- &eSpecial Discord Role'
    height: 0.3
  actions: {}
