location: lobby:6.500:73.500:-8.500
enabled: true
display-range: 48
update-range: 48
update-interval: 20
facing: 0.0
down-origin: true
pages:
- lines:
  - content: '&7- &bView'
    height: 0.3
  - content: '&7- &bVote'
    height: 0.3
  actions: {}
