location: lobby:45.5:71.0:-36.5
enabled: true
display-range: 48
update-range: 48
update-interval: 20
facing: 0.0
down-origin: true
pages:
- lines:
  - content: ' &7===== &aTop Time Played &7===== '
    height: 0.3
  - content: '&e#1. &a%fortresswars_leaderboards_time-played_1_name% &7-
      &a%fortresswars_leaderboards_time-played_1_value_TIME%'
    height: 0.3
  - content: '&e#2. &a%fortresswars_leaderboards_time-played_2_name% &7-
      &a%fortresswars_leaderboards_time-played_2_value_TIME%'
    height: 0.3
  - content: '&e#3. &a%fortresswars_leaderboards_time-played_3_name% &7-
      &a%fortresswars_leaderboards_time-played_3_value_TIME%'
    height: 0.3
  - content: '&e#4. &a%fortresswars_leaderboards_time-played_4_name% &7-
      &a%fortresswars_leaderboards_time-played_4_value_TIME%'
    height: 0.3
  - content: '&e#5. &a%fortresswars_leaderboards_time-played_5_name% &7-
      &a%fortresswars_leaderboards_time-played_5_value_TIME%'
    height: 0.3
  - content: '&e#6. &a%fortresswars_leaderboards_time-played_6_name% &7-
      &a%fortresswars_leaderboards_time-played_6_value_TIME%'
    height: 0.3
  - content: '&e#7. &a%fortresswars_leaderboards_time-played_7_name% &7-
      &a%fortresswars_leaderboards_time-played_7_value_TIME%'
    height: 0.3
  - content: '&e#8. &a%fortresswars_leaderboards_time-played_8_name% &7-
      &a%fortresswars_leaderboards_time-played_8_value_TIME%'
    height: 0.3
  - content: '&e#9. &a%fortresswars_leaderboards_time-played_9_name% &7-
      &a%fortresswars_leaderboards_time-played_9_value_TIME%'
    height: 0.3
  - content: '&e#10. &a%fortresswars_leaderboards_time-played_10_name% &7-
      &a%fortresswars_leaderboards_time-played_10_value_TIME%'
    height: 0.3
  - content: ' &a<-   &7===========   &a-> '
    height: 0.3
  actions:
    LEFT:
    - NEXT_PAGE
    - SOUND:UI_BUTTON_CLICK
    RIGHT:
    - PAGE:2
    - SOUND:UI_BUTTON_CLICK
- lines:
  - content: ' &7===== &aTop Credits &7===== '
    height: 0.3
  - content: '&e#1. &a%fortresswars_leaderboards_credits_1_name% &7- &a%fortresswars_leaderboards_credits_1_value_INT%'
    height: 0.3
  - content: '&e#2. &a%fortresswars_leaderboards_credits_2_name% &7- &a%fortresswars_leaderboards_credits_2_value_INT%'
    height: 0.3
  - content: '&e#3. &a%fortresswars_leaderboards_credits_3_name% &7- &a%fortresswars_leaderboards_credits_3_value_INT%'
    height: 0.3
  - content: '&e#4. &a%fortresswars_leaderboards_credits_4_name% &7- &a%fortresswars_leaderboards_credits_4_value_INT%'
    height: 0.3
  - content: '&e#5. &a%fortresswars_leaderboards_credits_5_name% &7- &a%fortresswars_leaderboards_credits_5_value_INT%'
    height: 0.3
  - content: '&e#6. &a%fortresswars_leaderboards_credits_6_name% &7- &a%fortresswars_leaderboards_credits_6_value_INT%'
    height: 0.3
  - content: '&e#7. &a%fortresswars_leaderboards_credits_7_name% &7- &a%fortresswars_leaderboards_credits_7_value_INT%'
    height: 0.3
  - content: '&e#8. &a%fortresswars_leaderboards_credits_8_name% &7- &a%fortresswars_leaderboards_credits_8_value_INT%'
    height: 0.3
  - content: '&e#9. &a%fortresswars_leaderboards_credits_9_name% &7- &a%fortresswars_leaderboards_credits_9_value_INT%'
    height: 0.3
  - content: '&e#10. &a%fortresswars_leaderboards_credits_10_name% &7- &a%fortresswars_leaderboards_credits_10_value_INT%'
    height: 0.3
  - content: ' &a<-   &7===========   &a-> '
    height: 0.3
  actions:
    LEFT:
    - PAGE:1
    - SOUND:UI_BUTTON_CLICK
    RIGHT:
    - PREV_PAGE
    - SOUND:UI_BUTTON_CLICK
