name: Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_to_production:
        description: "Option to deploy to production (Only for main branch)"
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
      
      # Decent Holograms
      - name: Deploy Decent Holograms Config
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_STAGE_USERNAME }}
          password: ${{ secrets.SFTP_STAGE_PASSWORD }}
          server: ${{ secrets.SFTP_STAGE_SERVER }}
          port: ${{ secrets.SFTP_STAGE_PORT }}
          local_path: config/plugins/DecentHolograms
          remote_path: /plugins
          sftp_only: true
