name: Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_to_production:
        description: "Option to deploy to production (Only for main branch)"
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Make build_files directory
        run: |
          mkdir build_files
          mkdir build_files/maps
          mkdir build_files/configs
          mkdir build_files/configs/config
          mkdir build_files/configs/plugins
          mkdir build_files/configs/plugins/DiscordSRV
          mkdir build_files/configs/plugins/FortressWars

      # Paper
      - name: Copy Files (Paper)
        run: |
          cp config/spigot.yml build_files/configs/spigot.yml
          cp config/paper-world-defaults.yml build_files/configs/config/paper-world-defaults.yml
          cp config/paper-global.yml build_files/configs/config/paper-global.yml

      # Advanced Ban
      - name: Copy Files (Advanced Ban)
        run: |
          cp -r config/plugins/AdvancedBan build_files/configs/plugins/AdvancedBan
      
      # Citizens
      - name: Copy Files (Citizens)
        run: |
          cp -r config/plugins/Citizens build_files/configs/plugins/Citizens
        
      # DamageIndicator
      - name: Copy Files (DamageIndicator)
        run: |
          cp -r config/plugins/DamageIndicator build_files/configs/plugins/DamageIndicator

      # DecentHolograms
      - name: Copy Files (DecentHolograms)
        run: |
          cp -r config/plugins/DecentHolograms build_files/configs/plugins/DecentHolograms

      # DiscordSRV - skip copying files that use environment variables
      - name: Copy Files (DiscordSRV)
        run: |
          cp -r config/plugins/DiscordSRV/messages.yml build_files/configs/plugins/DiscordSRV/messages.yml

      # FortressWars - skip copying files that use environment variables
      - name: Copy Files (FortressWars)
        run: |
          cp -r config/plugins/FortressWars/gamerules build_files/configs/plugins/FortressWars/gamerules
          cp -r config/plugins/FortressWars/settings.yml build_files/configs/plugins/FortressWars/settings.yml

      # PL-Hide
      - name: Copy Files (PL-Hide)
        run: |
          cp -r config/plugins/PL-Hide build_files/configs/plugins/PL-Hide

      # ServerListPlus
      - name: Copy Files (ServerListPlus)
        run: |
          cp -r config/plugins/ServerListPlus build_files/configs/plugins/ServerListPlus

      # SuperVanish
      - name: Copy Files (SuperVanish)
        run: |
          cp -r config/plugins/SuperVanish build_files/configs/plugins/SuperVanish
        
      # TAB
      - name: Copy Files (TAB)
        run: |
          cp -r config/plugins/TAB build_files/configs/plugins/TAB

      # Upload (Stage)
      - name: Upload (Stage)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_STAGE_USERNAME }}
          password: ${{ secrets.SFTP_STAGE_PASSWORD }}
          server: ${{ secrets.SFTP_STAGE_SERVER }}
          port: ${{ secrets.SFTP_STAGE_PORT }}
          local_path: build_files/configs/*
          remote_path: /.
          sftp_only: true
      
      # Upload (Production)
      - name: Upload (Production)
        if: github.ref_name == 'main' && inputs.deploy_to_production == true
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_PRODUCTION_USERNAME }}
          password: ${{ secrets.SFTP_PRODUCTION_PASSWORD }}
          server: ${{ secrets.SFTP_PRODUCTION_SERVER }}
          port: ${{ secrets.SFTP_PRODUCTION_PORT }}
          local_path: build_files/configs/*
          remote_path: /.
          sftp_only: true
